name: Skcrew
version: 4.0.0
main: com.lotzy.skcrew.spigot.Skcrew
description: Fork of Skript addon allows you make bedrock forms, integration with proxy, handle packets and some other
website: https://github.com/crewpvp/skcrew
depend: [Skript]
softdepend: [Floodgate, ViaVersion, Skent, skript-gui, Bitshift, skript-db]
authors: [avesatana, Lotzy, w0w0, MiguVT, Olyno, Govindas, APickledWalrus, MrsDarth, Pesekjak]
api-version: "1.13"